services:
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: catfact-worker
    restart: always
    depends_on:
      - azurite
    environment:
      - ConnectionStrings__AzureStorage=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;
    volumes:
      - ./output:/app/output

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: catfact-azurite
    restart: always
    ports:
      - "10000:10000"
    volumes:
      - azurite_data:/data
    command: "azurite-blob --blobHost 0.0.0.0 --blobPort 10000 --location /data"

volumes:
  azurite_data: